---
title: "Testing AWS service integrations using LocalStack"
date: 2023-05-04T09:39:58+05:30
draft: false
description: This guide will explain how to test Spring Cloud AWS applications using LocalStack and Testcontainers.
repo: https://github.com/testcontainers/tc-guide-testing-aws-service-integrations-using-localstack
languages:
  - Java
tags:
  - spring-boot
  - localstack
  - aws
---
:toc:
:toclevels: 2
:codebase: https://raw.githubusercontent.com/testcontainers/tc-guide-testing-aws-service-integrations-using-localstack/main

In this guide, you will learn how to

* Create a Spring Boot application with Spring Cloud AWS integration
* Use AWS S3 and SQS services
* Test the application using Testcontainers and LocalStack

== Prerequisites
* Java 17+
* Your favorite IDE (Intellij IDEA, Eclipse, NetBeans, VS Code)
* A Docker environment supported by Testcontainers https://www.testcontainers.org/supported_docker_environment/

== What we are going to achieve in this guide
We are going to create a Spring Boot application and use https://awspring.io/[Spring Cloud AWS] to work with
AWS S3 and SQS services. We are going to send a message to an SQS queue and implement a listener
to consume the messages and save the payload data in a S3 bucket.
We are going to test this application using Testcontainers and https://localstack.cloud/[LocalStack].

== Getting Started
Spring Cloud AWS provides higher-level abstraction on top of AWS Java SDK V2 and tight integration
with Spring Boot following the Spring programming model.

LocalStack is a fully functional local cloud stack to develop and test your AWS cloud and 
serverless applications.

Let's create a Spring Boot application from https://start.spring.io/[Spring Initializr] by selecting *Testcontainers* dependency.
Currently, Spring Cloud AWS starters are not available on Spring Initializr, so we need to manually
add the required dependencies.

Let's configure *spring-cloud-aws-dependencies* Bill Of Material (BOM) and add *S3*, *SQS* starters.
Testcontainers provide a https://testcontainers.com/modules/localstack/[LocalStack module]
which we are going to use for testing AWS service integrations.
Also, we are going to use http://www.awaitility.org/[Awaitility] for testing SQS asynchronous processing.

If you are using *Gradle* build tool, you should have the dependencies configured in *build.gradle* file as follows:

[source,groovy]
----
include::{codebase}/build.gradle[lines="22..42"]
----

For complete code, please refer to the GitHub repository
https://github.com/testcontainers/tc-guide-testing-aws-service-integrations-using-localstack

We are going to work with a SQS queue and S3 bucket. To make the queue and bucket names configurable,
let's create a configuration properties class as follows:

[source,java]
----
include::{codebase}/src/main/java/com/testcontainers/demo/ApplicationProperties.java[]
----

== Implement StorageService to work with S3 service

Spring Cloud AWS provides higher-level abstractions like *S3Client* and *S3Template*
with convenience methods for performing the most common tasks such as uploading/downloading files,
generating signed URLs etc.

Let us create a *StorageService.java* class to upload and download files using *S3Template* as follows:

[source,java]
----
include::{codebase}/src/main/java/com/testcontainers/demo/StorageService.java[]
----

== Implement SQS message sender and listener
Spring Cloud AWS provides higher-level abstraction *SqsTemplate* on top of AWS Java SDK *SqsAsyncClient*
and *@SqsListener* annotation driven listener support to work with SQS queues.

Let's create a record *Message.java* that represents the message payload we are going to send
to the SQS queue as follows:

[source,java]
----
include::{codebase}/src/main/java/com/testcontainers/demo/Message.java[]
----

Create *MessageSender.java*, which internally uses SqsTemplate, to publish messages to
the SQS queue as follows:

[source,java]
----
include::{codebase}/src/main/java/com/testcontainers/demo/MessageSender.java[]
----

Create *MessageListener.java* and implement a SQS queue message handler method annotated
with *@SqsListener* specifying which queue(s) to listen to.


[source,java]
----
include::{codebase}/src/main/java/com/testcontainers/demo/MessageListener.java[]
----

Note that we have used *SpEL* expression *$\{app.queue}* to configure the queue name using
the configured property value instead of hard-coding the queue name.

When a message is published to the SQS queue, Spring handles unmarshalling the payload data
into a *Message* object, and we are uploading the message content into S3 bucket with message's unique key.

== Write integration test using LocalStack
We can spin up a container from https://hub.docker.com/r/localstack/localstack[LocalStack Docker image] and configure the following
Spring Cloud AWS properties to talk to LocalStack container instead of the actual AWS services.

[source,properties]
----
spring.cloud.aws.s3.endpoint=http://localhost:4566
spring.cloud.aws.sqs.endpoint=http://localhost:4566
spring.cloud.aws.credentials.access-key=noop
spring.cloud.aws.credentials.secret-key=noop
spring.cloud.aws.region.static=us-east-1
----

However, for testing it would be better to use an ephemeral container that starts on a
random available port so that we can run multiple builds on CI in parallel without having
port conflict issues. Testcontainers provide a LocalStack module that would help us to achieve this easily.

We can create a SpringBoot integration test that will start a LocalStack container and
configure the Spring Cloud AWS properties as follows:

[source,java]
----
include::{codebase}/src/test/java/com/testcontainers/demo/MessageListenerTest.java[lines="22..48,78"]
----

We have used Testcontainers JUnit 5 Extension annotations *@Testcontainers* and *@Container*
to spin up a *LocalStackContainer* instance. Then we obtain the dynamic S3 and SQS endpoint URLs,
region, access and secret keys from the container instance and configured Spring Cloud AWS
configuration properties using *DynamicPropertyRegistry* mechanism.

Before writing our test, we need to create a SQS queue and S3 bucket. We can use *@BeforeAll* callback
method to create the necessary resources (S3 buckets or SQS queues etc) by using
*localStack.execInContainer()* API as follows:

[source,java]
----
include::{codebase}/src/test/java/com/testcontainers/demo/MessageListenerTest.java[lines="49..53"]
----

We have used *localStack.execInContainer()* API to run commands inside the container and used *awslocal* CLI tool,
that comes pre-installed with LocalStack Docker image, to create the AWS resources.

Finally, we can write our test by publishing a message to the SQS queue which should be handled
by the listener and persist the message content in the S3 bucket. We will use Awaitility
to wait a maximum of 10 seconds to verify whether the expected message is present in the
S3 bucket with the key or not.

The complete test would look like this:

[source,java]
----
include::{codebase}/src/test/java/com/testcontainers/demo/MessageListenerTest.java[]
----

We have created a Message instance with a random UUID as a unique identifier and published the message
to the SQS Queue. When the listener receives the message, the message content will be stored in S3 bucket
with the random UUID as key. Then we are verifying whether there is an entry in the bucket with
the expected key and the content is equal to what we sent or not.

== Run tests

[source,shell]
----
# If you are using Maven
./mvnw test

# If you are using Gradle
./gradlew test
----

You should see the LocalStack Docker container is started and the test should PASS.
You can also notice that after the tests are executed, the containers are stopped and removed automatically.

== Summary
LocalStack enables developing AWS services based applications locally and Testcontainers LocalStack module
makes it simpler to write integration tests by using LocalStack ephemeral containers.

To learn more about Testcontainers visit http://testcontainers.com

== Further Reading
* https://testcontainers.com/guides/testing-spring-boot-kafka-listener-using-testcontainers/[Testing Spring Boot Kafka Listener using Testcontainers]
* https://testcontainers.com/guides/getting-started-with-testcontainers-for-java/[Getting started with Testcontainers for Java]
* https://www.testcontainers.org/modules/localstack/[Testcontainers LocalStack Module]
